/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_man_sys;

import javax.swing.JOptionPane;
import java.awt.*;
import java.util.Objects;

/**
 *
 * @author isaac
 */
public class Update_Students extends javax.swing.JFrame {

    /**
     * Creates new form Add_Student
     */
    String gender;
    
    
    public Update_Students() {
        initComponents();
        setLocationRelativeTo(null);
        
        
            
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        firstname_Field = new javax.swing.JTextField();
        lastname_Field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        male_G = new javax.swing.JRadioButton();
        female_G = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        programme_Field = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        studentIDField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        firstname_Field.setBackground(new java.awt.Color(255, 255, 255));
        firstname_Field.setForeground(new java.awt.Color(0, 0, 0));
        firstname_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstname_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstname_FieldFocusLost(evt);
            }
        });

        lastname_Field.setBackground(new java.awt.Color(255, 255, 255));
        lastname_Field.setForeground(new java.awt.Color(0, 0, 0));
        lastname_Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastname_FieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastname_FieldFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", Font.BOLD, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPDATE STUDENT");

        jLabel2.setFont(new java.awt.Font("sanserif", Font.BOLD, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Firstname:");

        jLabel3.setFont(new java.awt.Font("sanserif", Font.BOLD, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lastname:");

        jLabel4.setFont(new java.awt.Font("sanserif", Font.BOLD, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Programme:");

        jLabel5.setFont(new java.awt.Font("sanserif", Font.BOLD, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender:");

        gender_group.add(male_G);
        male_G.setFont(new java.awt.Font("sanserif", Font.BOLD, 14)); // NOI18N
        male_G.setForeground(new java.awt.Color(255, 255, 255));
        male_G.setText("Male");
        male_G.addActionListener(this::male_GActionPerformed);

        gender_group.add(female_G);
        female_G.setFont(new java.awt.Font("sanserif", Font.BOLD, 14)); // NOI18N
        female_G.setForeground(new java.awt.Color(255, 255, 255));
        female_G.setText("Female");
        female_G.addActionListener(this::female_GActionPerformed);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("sanserif", Font.BOLD, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setFont(new java.awt.Font("sanserif", Font.BOLD, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" <    BACK ");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.red));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        programme_Field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Choose programme --", "Hospitality", "Computer Networking", "Computer Science", "Mechanical Engineering", "Purchasing and Supply", "Computer Engineering" }));

        jLabel7.setFont(new java.awt.Font("sanserif", Font.BOLD, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student ID:");

        studentIDField.setBackground(new java.awt.Color(255, 255, 255));
        studentIDField.setForeground(new java.awt.Color(0, 0, 0));
        studentIDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentIDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentIDFieldFocusLost(evt);
            }
        });
        studentIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studentIDFieldKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Cambria", Font.BOLD, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("NOTE: Student ID should only contain Digits.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel7))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lastname_Field, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstname_Field, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(male_G)
                                        .addGap(37, 37, 37)
                                        .addComponent(female_G))
                                    .addComponent(programme_Field, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(studentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(300, 300, 300))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(studentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(firstname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastname_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(programme_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male_G)
                    .addComponent(female_G)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (studentIDField.getText().equals("")
                ||firstname_Field.getText().equals("")
                || lastname_Field.getText().equals("")
                || Objects.equals(programme_Field.getSelectedItem(), "-- Choose programme --")
                || gender.equals("")) {
            JOptionPane.showMessageDialog(this, "Empty fields, please fill all fields", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String studID="AD"+studentIDField.getText();
            String firstname = firstname_Field.getText();
            String lasttname = lastname_Field.getText();
            String programme =(String) programme_Field.getSelectedItem();
            Update_DB add_DB = new Update_DB(studID,firstname, lasttname, programme, gender, this);
            studentIDField.setText("");
            firstname_Field.setText("");
            lastname_Field.setText("");
            programme_Field.setSelectedIndex(0);
            gender = "";
            gender_group.clearSelection();
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void female_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_GActionPerformed
        gender = "Female";
    }//GEN-LAST:event_female_GActionPerformed

    private void male_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male_GActionPerformed
        gender = "Male";
    }//GEN-LAST:event_male_GActionPerformed

    private void firstname_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstname_FieldFocusGained

    }//GEN-LAST:event_firstname_FieldFocusGained

    private void lastname_FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastname_FieldFocusGained

    }//GEN-LAST:event_lastname_FieldFocusGained

    private void firstname_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstname_FieldFocusLost

    }//GEN-LAST:event_firstname_FieldFocusLost

    private void lastname_FieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastname_FieldFocusLost

    }//GEN-LAST:event_lastname_FieldFocusLost

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void studentIDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDFieldFocusGained

    private void studentIDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDFieldFocusLost

    private void studentIDFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIDFieldKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_studentIDFieldKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton female_G;
    private javax.swing.JTextField firstname_Field;
    private javax.swing.ButtonGroup gender_group;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname_Field;
    private javax.swing.JRadioButton male_G;
    private javax.swing.JComboBox<String> programme_Field;
    private javax.swing.JTextField studentIDField;
    // End of variables declaration//GEN-END:variables
}
